---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fenix
# description will be included in the image's metadata
description: "fen's linux"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/sericea-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - yalter/niri
        - avengemedia/danklinux
        - errornointernet/quickshell
    install:
      packages:
        - niri
        - ghostty
        - quickshell-git
        - mpd
        - dolphin
        - qt5ct
        - qt6ct
        - plasma-breeze
        - ark
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - sway
        - sway-config-fedora
        - swaybg
        - swayidle
        - swaylock
        - sddm
        - sddm-wayland-sway
        - blueman
        - Thunar
        - xarchiver
        - xdg-desktop-portal-kde
        - waybar
        - grim
        - slurp
        - pavucontrol
        - foot

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen
          - org.gnome.Loupe
          - org.kde.Haruna
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
