---
name: fenix
description: FEn's uNIX (but it's actually linux lol)

base-image: ghcr.io/secureblue/sericea-main-hardened
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # files/system/*

  - type: dnf
    repos:
      nonfree: rpmfusion
      copr:
        - name: yalter/niri
          chroot: fedora-42-x86_64
        - name: avengemedia/danklinux
          chroot: fedora-42-x86_64
        - name: errornointernet/quickshell
          chroot: fedora-42-x86_64
    install:
      packages:
        - niri
        - ghostty
        - quickshell-git
        - mpd
        - dolphin
        - qt5ct
        - qt6ct
        - plasma-breeze
        - ark
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - sway
        - sway-config-fedora
        - swaybg
        - swayidle
        - swaylock
        - sddm
        - sddm-wayland-sway
        - blueman
        - Thunar
        - xarchiver
        - xdg-desktop-portal-kde
        - waybar
        - grim
        - slurp
        - pavucontrol
        - foot

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          - app.zen_browser.zen
          - org.gnome.Loupe
          - org.kde.Haruna

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
